language: python
python:
  - "3.8"

# Install dependencies
install:
  - pip install black

stage: formatter
- black --check example.py

# Run the script
script:
- CHK=$(echo $?)
- echo $CHK
# if: CHK==1 than python example.py
  
