language: python
python:
  - "3.8"

# Install dependencies
install:
  - pip install black

# Run the script
script:
- black --check example.py
- check = $(echo $?)
- echo $check
# if: $check = 0 than python example.py
  
