language: python
python:
  - "3.8"

# Install dependencies
install:
  - pip install black

# Run the script
script:
  - black --check example.py
  allow_failures: 
   - if: $=1 
  - python example.py
  
