language: python
python:
  - "3.8"

# Install dependencies
install:
  - pip install black

jobs:
 include:
  - stage: formatter #this is our quality gate
    script: black --check example.py

# Run the script
  - stage: display
    script:
    python example.py

  
